### PR TITLE
Fix: don't force weburl parameter in config/dev.php

### PR DESCRIPTION
**Pull request by Gounlaf**

### CODE REVIEW

**Comment by blackandred** [comment]
Hello,

Thank you very much for the contribution.

What do you think to maybe better insert a block that would allow to customize the whole `dev` environment like in `prod` environment?

```
if (is_file(__DIR__ . '/dev.custom.php')) {
    require __DIR__ . '/dev.custom.php';
}
```

Then we can add `dev.custom.php` to the .gitignore and have custom dev config :wink:

**Comment by Gounlaf** [comment]
Hi,

> What do you think to maybe better insert a block that would allow to customize the whole `dev` environment like in `prod` environment?

It would be a good solution.

**Comment by blackandred** [comment]
Hi,
So, feel free to update the PR with a next commit so I could accept it :smile: 
Thanks for the contribution.

**Comment by Gounlaf** [comment]
Just a thing about this particular config key: why do you force it? In `prod.php`, it's already set correctly (and it follow default parameters provided in README - localhost/0.0.0.0:8888)

`$app['weburl'] = $protocol . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost:8888');`

Php built-in server, nginx, apache (at least theses 3) correctly fill HTTP_HOST value.

That's why I think it should not be set manually by default.



But, yes, a dev.custom.php like for prod is a good idea (and I can make a PR for that if necessary)

**Comment by blackandred** [comment]
Actually sorry, I don't remember, probably it as a fix for the CI.
Generally sorry that the commits are not smaller, I was always working on all projects alone and had to implement everything by my own without any help so had not that much time.

It seems that the construction from `prod.php` would work now :+1: 
So I suggest to remove the line you suggested, additionally put the block that would allow overriding `dev` environment settings locally :wink:

**Comment by Gounlaf** [comment]
> Actually sorry, I don't remember, probably it as a fix for the CI.

Don't be! I made another PR for customizing dev config (https://github.com/Wolnosciowiec/file-repository/pull/9)

**Pull request merged**
