### PR TITLE
Clean up + Heroku integration

### PR DESCRIPTION
**Pull request by blackandred**
Hello,

I added the cloud hostings integration (including Heroku), added some documentation and made a clean up with images in the documentation directory.

### CODE REVIEW

**Comment by blackandred** [comment]
The tests will not work fully because they rely on what is on master unfortunately.
Images were moved to other directory, so the tests will start passing when merged to master.

**Comment by blackandred** [comment]
@Gounlaf Would you like to take a look? :stuck_out_tongue:

**Comment by Gounlaf** [comment]
About configuration, since you need to "clean it up" for Heroky, why not use [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) ?

**Comment by blackandred** [comment]
I know `phpdotenv` but I don't see a point of using it here. 
There is a mixed configuration - PHP way for more advanced usage, and the configuration by environmental variables.

Phpdotenv is reading variables from `.env` file which is a kind of emulation of Unix/Linux behavior, but on cloud eg. Heroku we do not need it because it's native.

Also we cannot switch to configuration via `.env` because we will be providing a possibility to inject Flysystem objects which will not be possible without a PHP configuration file.

**Comment by Gounlaf** [comment]
👍 

I see "nothing" strange / weird. I've checkout the branch to see modifications "in action", but I think you can merge :)

**Comment by blackandred** [comment]
Ok, thank you :stuck_out_tongue:

**Pull request merged**
