### PR TITLE
Sync dev front-controller with prod (allow images to be fetched...)

### PR DESCRIPTION
**Pull request by Gounlaf**

### CODE REVIEW

**Comment by blackandred** [comment]
So, you mean this fixes the problem that in PHP Internal Webserver the images were not rendered properly?

**Comment by Gounlaf** [comment]
@blackandred: with this "agressive" rules, I can't download an uploaded image (https://github.com/Wolnosciowiec/file-repository/issues/12#issuecomment-299659648)

And, why this rules is on `dev` env and not in `prod`?

=> We should allow images serves with route `GET /public/download/{imageName}`, and deny everything else. On a "dedicated server", this rules is usually on web server configuration; but for shared, I agree that it should be in the front controllers too :)

**Comment by blackandred** [comment]
I agree there are some problems but I noticed this only on the PHP's builtin webserver, so this was a minor issue. I'm happy you fixed it then. Thank you.

The reason why this rule was on `dev` was a some workaround for the PHP's builtin webserver, there is a possibility to run it on a directory and on a file, one of methods were working with this workaround. But if you find this patch to be working with the `composer run` then it would be nice :smile:

**Comment by Gounlaf** [comment]
> I'm happy you fixed it then. Thank you.
> 
> The reason why this rule was on dev was a some workaround for the PHP's builtin webserver, there is a possibility to run it on a directory and on a file, one of methods were working with this workaround. But if you find this patch to be working with the composer run then it would be nice 😄

I will check again, 'cause I don't use the built-in server. This PR may have re-introduce "bug"

**Comment by Gounlaf** [comment]
😅 it still works

**Comment by blackandred** [comment]
Thank you for testing this.

**Pull request merged**
